### PR TITLE
folia

### PR DESCRIPTION
**Pull request by ewof**
tested on paper and folia 1.20.1
uses [Universal Scheduler](https://github.com/Anon8281/UniversalScheduler)

### CODE REVIEW

**Comment by LeonMangler** [comment]
Thank you for your pull request! I have asked Universal Scheduler's author to add a license to their project so we can determine whether it can be used in SuperVanish!

**Comment by ewof** [comment]
he added MIT license

**Comment by ewof** [comment]
@LeonMangler

**Comment by LeonMangler** [comment]
Hey, I don't have much time currently so it will take a while to go through all the PR's one-by-one, but I will get back to this eventually! I have taken a brief look at Universal Scheduler and it does look like a convenient library for adding folia support.

**Comment by ewof** [comment]
closing this bc the folia inquisitors one is open

**Pull request closed without merging**
