### PR TITLE
Several additions and bug fixes

### PR DESCRIPTION
**Pull request by crazycat256**
Updated version of [this PR](https://github.com/LeonMangler/SuperVanish/pull/75), makes the following changes:

- Update to PaperMC API (necessary for several events)
- Reorganize certain features
- Improve SilentOpenChest: the player can no longer see when switching to spectator mode, which prevents him from flying or going through blocks
- Add HideAdvancementMessages: hides the advancement messages from vanished players
- Add DisableMsgCommand: prevent players from sending private messages to vanished players
- Disable several events for vanished players
- Fix a bug that prevented ExternalInvisibility from working properly since 1.19.4
- Fix a bug that leaked vanished players around a player when he logged in

### CODE REVIEW

**Comment by LeonMangler** [comment]
Hey, thank your for your pull request, I appreciate it! There are lots of cool improvements, which is great! I am sure it took a lot of time. However, it is difficult for me to merge it into the master branch right away, because there are so many changes at once, making it extremely tedious to test for me. Furthermore, I would like SuperVanish to support non-paperspigot servers and old servers, which means paperspigot-based API and new cutting-edge spigot should not be used without a fallback.
It would be very cool if you could make separate pull requests for a few of the individual changes made in this big PR. Regardless, great contribution!

**Comment by crazycat256** [comment]
Hello, thank you for your reply.
I understand the problem linked to the size of the PR, I'll see if I can separate it (but having little time to devote to it at the moment, I won't be able to do everything quickly).

As for the API change, since PaperMC's API is an addition to Spigot's, the plugin will still work on non-paper servers. The only difference will be that Paper events won't be called (I tested on a recent version of spigot). As these events are the only way to suppress the appearance of mobs by vanish players, it seems to me that adding this as a feature available only to PaperMC servers is the best option.

I'll try to make separate PRs for the features in this one.

**Comment by Justman100** [comment]
@LeonMangler

What here now?

**Comment by crazycat256** [comment]
Outdated PR

**Comment by Justman100** [comment]
> Outdated PR

You could also delete your fork

**Comment by Justman100** [comment]
@crazycat256

**Pull request closed without merging**
