### PR TITLE
Update to 1.20.1, several additions and bug fixes

### PR DESCRIPTION
**Pull request by crazycat256**
**This PR contains the following changes:**

- Update to 1.20.1
- Update to PaperMC API (necessary for several events)
- Reorganize certain features
- Improve SilentOpenChest: the player can no longer see when switching to spectator mode, which prevents him from flying or going through blocks
- Add HideAdvancementMessages: hides the advancement messages from vanished players
- Add DisableMsgCommand: prevent players from sending private messages to vanished players
- Disable several events for vanished players
- Fix a bug that prevented ExternalInvisibility from working properly since 1.19.4
- Fix a bug that caused some features not to activate in 1.20
- Fix a bug that leaked vanished players around a player when he logged in

### CODE REVIEW

**Comment by Atticuss26** [comment]
please add this

**Comment by Kaerix** [comment]
bump

**Comment by NotSharwan** [comment]
bump

**Comment by crazycat256** [comment]
I had to close this PR and open another one to use the latest commit, the updated version is [here](https://github.com/LeonMangler/SuperVanish/pull/76).

**Pull request closed without merging**
