### PR TITLE
Disable tipping of dripleafs for vanished players. 

### PR DESCRIPTION
**Pull request by ARR4NN**
**Additions**:
- Added code to stop drip leafs tipping when vanished
- Added the config option to enable/disable this.

### CODE REVIEW

**Comment by BetTD** [comment]
Dripleaves were added to the game in 1.17, shouldn't this be using a new feature option called 'oneDotSeventeenOrHigher'? My PR #68 added this feature option but it was not merged in *directly*, parts of my code were copied over manually it seems, so the option wasn't implemented.

**Comment by LeonMangler** [comment]
Hey, thanks for your PR! Dripleaves were indeed added later so could you please change that to 1.17?

**Comment by BetTD** [comment]
@ARR4NN Fetch the latest changes on your fork and use the ``oneDotDeventeenOrHigher`` requirement, that should do it!

**Comment by ARR4NN** [comment]
Thank you will do 🫡

**Pull request merged**
