### PR TITLE
Update for 1.19.3

### PR DESCRIPTION
**Pull request by brothanb**
Fix Unknown Exception (Null Pointer Exception) errors on 1.19.3 with latest protocol lib.

Update to Spigot 1.19.3 for dependency.

### CODE REVIEW

**Comment by Wolvinny** [comment]
Seems like this version causes all of the players on vanilla clients to be kicked for 'Chat validation failure'. I dont really see how vanish can cause this but it started when i added it and stopped when i removed it. the latest 'official' build, the one with the protocllib errors, works fine. Players using optifine clients also dont seem to be affected

**Comment by brothanb** [comment]
> Seems like this version causes all of the players on vanilla clients to be kicked for 'Chat validation failure'. I dont really see how vanish can cause this but it started when i added it and stopped when i removed it. the latest 'official' build, the one with the protocllib errors, works fine. Players using optifine clients also dont seem to be affected

I've seen that on our SMP with the current release of SV on 1.19.2 when doing simple things like changing game modes.

It's more likely there are more changes required around the changes to chat 1.19+.

Also, to be honest, I didn't fully test the PR against all of the plugins out there that are SV aware (not that I have a setup where I could).

**Comment by kaxlabs** [comment]
Not having the "Chat validation failure" on my end, but I do cancel the chat events to use my own implementation. MarkVanishedPlayersAsSpectators still appears to be broken on this PR though.

**Comment by LcyDev** [comment]
I'm having this issue on 1.19.3
https://paste.gg/p/ConaII_/7816944651de4b399aaddc85fda7c0b9

**Comment by MrClean1337** [comment]
> I'm having this issue on 1.19.3 https://paste.gg/p/ConaII_/7816944651de4b399aaddc85fda7c0b9

Same for me, im using paper

**Comment by CommandoEchino** [comment]
Can confirm, same issue as @LcyDev and @MrClean1337:

https://paste.gg/p/anonymous/c058e86f68934b74b71f50dfe75325d4

**Comment by LeonMangler** [comment]
Hey, thanks for your PR! I have kind of given up on MarkVanishedPlayersAsSpectators and using the tablist packet listeners, since they seem to cause endless trouble with lag issues and breaking on major updates.
As for the chat validation failure issue, I think this is a general Spigot/PaperSpigot bug that affects other vanish plugins as well. PaperSpigot has recently tried to fix it, but apparently without success. I'll give it a bit more time since Player#hide/showPlayer is standard Spigot API so they are likely to fix it eventually.

**Comment by Latch93** [comment]
@LeonMangler Can I help update to 1.20 in any way? 
I updated it locally, but I can't make a PR or anything. It's only a couple lines.

**Pull request closed without merging**
